version: "3.8"

services:
  user-service:
    build: ./services/user-service
    ports:
      - "5001:5001"
    depends_on:
      - postgres
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: userdb
    networks:
      - app-network

  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
